# Generated by Django 3.1.1 on 2021-07-23 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('image_path', models.CharField(max_length=600)),
                ('min_price', models.FloatField()),
                ('last_auction_price', models.FloatField(blank=True, null=True)),
                ('auction_start_date_time', models.DateTimeField(blank=True, null=True)),
                ('auction_finish_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_bid_amount', models.FloatField(blank=True, null=True)),
                ('left_bid_amount', models.FloatField(blank=True, null=True)),
                ('fund', models.FloatField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.FloatField(blank=True, null=True)),
                ('auto_bidding_status', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_users',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_user',
            field=models.ManyToManyField(through='catalog.ItemUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
